name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Cache bundle
      # cache will change when runner.os or requirements.txt changed
      uses: actions/cache@v2
      with:
        path: |
          $HOME/.cache/pip
          $HOME/.rqalpha/bundle
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        # Install Test Deps
          pip install -U pip
          pip install "numpy>=1.15.4"

