name: Rqalpha test
on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    # Checks out a copy of your repository on the ubuntu-latest machine
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Install TA-Lib
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
        # Install Test Deps
          pip install -U pip
          pip install "numpy>=1.15.4"
          pip install TA-Lib
          pip install coveralls
          pip install -U setuptools
          pip install ipython==5.3.0
          pip install --prefer-binary .
    - name: Unit Test
      run:  |
          rqalpha download-bundle
          coverage run --source=rqalpha test.py
          ls -al $HOME/.rqalpha/
          ls -al $HOME/.rqalpha/bundle/
    - name: Cache bundle
      # cache will change when runner.os or requirements.txt changed
      uses: actions/cache@v2
      with:
        path: |
          $HOME/.cache/pip
          $HOME/.rqalpha/bundle
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Test
  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true